### ISSUE TITLE
Write call fails TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by ThomasNucleus** [robroypt/odoo-client#2]
I'm trying to do a write function call, however this is the response I get back:

> [
	'faultCode' => (int) 1,
	'faultString' => 'Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/service/wsgi_server.py", line 56, in xmlrpc_return
    result = odoo.http.dispatch_rpc(service, method, params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 38, in dispatch
    res = fn(db, uid, *params)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 157, in execute_kw
    return execute(db, uid, obj, method, *args, **kw or {})
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 164, in execute
    res = execute_cr(cr, uid, obj, method, *args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 153, in execute_cr
    return odoo.api.call_kw(recs, method, args, kw)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 678, in call_kw_multi
    recs = self.with_context(context or {}).browse(ids)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4792, in browse
    return self._browse(ids, self.env, prefetch)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 4779, in _browse
    prefetch[cls._name].update(ids)
TypeError: unhashable type: 'list'
'
]

My code:

> $odooAccountIDs = [9];
> 
> $client->write('investment.ac', $odooAccountIDs,
>             ['current_risk_profile_id' => $account->current_risk_profile_id]
>  );

I am able to do create and search calls with no issues

**Comment by ThomasNucleus** [comment]
Figured it out, made a pull request #3
